config/routes.rb
Rails.application.routes.draw do
  resources :photos
  resources :subscriptions
  resources :comments
  devise_for :users

  root 'events#index'

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
    post :show, on: :member
  end

  resources :users, only: [:show, :update, :edit]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos, dependent: :destroy

  validates :title, presence: true, length: { maximum: 255 }
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  before_action :set_event, only: [:show]
  before_action :set_current_user_event, only: [:edit, :update, :destroy]
  before_action :password_guard!, only: [:show]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: I18n.t("controllers.events.created") }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def set_current_user_event
      @event = current_user.events.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
    end

    def password_guard!
      return true if @event.pincode.blank?
      return true if signed_in? && current_user == @event.user

      if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
        cookies.permanent["event_#{@event.id}_pincode"] = params[:pincode]
      end

      unless @event.pincode_valid?(cookies.permanent["event_#{@event.id}_pincode"])
        flash.now[:alert] = I18n.t('controllers.events.wrong_pincode')
        render 'password_form'
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">

    <%= content_tag 'div', '', class: 'event-background',
      style: "background-image: url(#{asset_path('event_thumb.jpg')})" %>

    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <h3><small><%= l event.datetime,  format: :short%></small></h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>
        <div>
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%# Паршиал дляотображения формы создания нового события %>
<%= form_for(@event) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :pincode %>
    <%= f.text_area :pincode, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
    или <%= link_to 'вернуться', :back %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="container">
<h1>Редактирование события</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>

    <div class="buffer-top">
      <%= link_to 'Удалить', event_path(@event), data: { confirm: I18n.t('are_you_sure') }, method: :delete,
      class: 'btn btn-danger ' %>
    </div>
  </div>
</div>
</div>

app/views/events/index.html.erb
<div class="container">
<h1>События</h1>

<div class="buffer-both">
  <%= link_to 'Создать событие', new_event_path, class: 'btn btn-success' %>
</div>

<div class="row buffer-bottom">
  <%# Рендерим сразу массив событий, каждый в паршиале 'events/event' %>
  <%= render partial: 'events/event', collection: @events %>
</div>
</div>

app/views/events/new.html.erb
<div class="container">
<h1>Новое событие</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>
</div>

app/views/events/password_form.html.erb
<div class='container'>
<h1><%= t("activerecord.attributes.event.access_by_pincode")%></h1>

<%= form_tag('', method: 'post') do |f| %>
  <div class="form-group">
    <%= text_field_tag :pincode, params[:pincode], class: 'form-control',
      placeholder: t("activerecord.attributes.event.pincode") %>
  </div>

  <div class="actions mb-2">
    <%= submit_tag t("activerecord.attributes.event.send"), class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to t("activerecord.attributes.event.to_main"), events_path %>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="event">
  <div class="event-info row">
    <div class="col-md-12">
      <%# Выводим произвольную фотку в качестве фона для шапки события %>
      <%= content_tag 'div', '', class: 'event-background',
        style: "background-image: url(#{event_photo(@event)})" %>

      <div class="event-info-inner row">
        <div class="col-md-6">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :short %></h3>
            <h3>
              <small><%= link_to @event.address,
                "https://yandex.ru/maps/?text=#{@event.address}" %></small>
            </h3>
            <p><%= @event.description %></p>
          </div>

          <% if current_user_can_edit?(@event) %>
            <div class="buffer-both">
              <%= link_to 'Изменить', edit_event_path(@event),
                class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">

    <div id="map"
      data-address="<%= @event.address %>"
      style="width: 100%; height: 200px;">
    </div>
      <div class="event-photos">
        <%# Выводим все фотографии события %>
        <div class="event-photos-gallery">
          <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
        </div>

        <%# Рисуем форму для добавления новой фотографии %>
        <div class="event-photo-form">
          <%= render partial: 'photos/form', locals: {photo: @new_photo || @event.photos.build} %>
        </div>
      </div>

      <div class="event-comments buffer-top">
        <%= render partial: 'comments/form',
          locals: {comment: @new_comment || @event.comments.build} %>

        <div class="buffer-both">
          <%= render partial: 'comments/comment',
            collection: @event.comments.except(@new_comment) %>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="event-owner">
        <h4>Зовет:</h4>
        <p><%= render partial: 'users/user', object: @event.user %></p>
      </div>
      <% if @event.subscriptions.exists? %>
      <div class="event-subscriptions">
        <h4>Пойдут:</h4>
        <div>
          <p>
          <%= render partial: 'subscriptions/subscription',
            collection: @event.subscriptions.except(@new_subscription) %>
          </p>
        </div>
      </div>
      <% end %>
      <% unless current_user_can_edit?(@event) %>
      <div class="event-subscription-form">
        <h4>Я пойду:</h4>
        <div>
          <%= render partial: 'subscriptions/form', locals: {
            subscription: @new_subscription || @event.subscriptions.build
          } %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  </div>
</div>